spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/biblio
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/